### ISSUE TITLE
strict mode

### ISSUE THREAD

**Issue by johngriffin** [krismuniz/botkit-sms#1]
When running the example I get the following error, which I fixed by adding "use strict" to the top of index.js:

```
  let twilioSMS = Botkit(configuration || {})
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/john/dev/botkit-twilio-test/index.js:6:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by krismuniz** [comment]
This happens when Node is below v6.0.0 since block-scoped declarations are not supported outside strict mode. Adding "use strict" in `/lib/` and `/example` files and fixing now.

Thank you!

**Comment by krismuniz** [comment]
Should be fixed now. https://github.com/krismuniz/botkit-sms/commit/4b880f6b94652d724b7e5882a683a3ef390ab993 :)

Update the the `npm` package and you should not have this problem. :)
