### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by johngriffin** [krismuniz/botkit-sms#2]
index.js requires "express" and "body-parser" but these are not included in package.json.  This causes the following error to be thrown.  

```
const express = require('express')

module.js:327
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/john/dev/botkit-twilio-test/node_modules/botkit-sms/lib/index.js:3:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by krismuniz** [comment]
@johngriffin Thank you! I can't believe I let this happen. Fixing it now. :)

**Comment by krismuniz** [comment]
Should be fixed now. https://github.com/krismuniz/botkit-sms/commit/4b880f6b94652d724b7e5882a683a3ef390ab993 :)

Update the the `npm` package and you should not have this problem. :)
